---
project: DEMO Env.
kind: PIPELINE
name: TEST BluePrint Deploy
icon: organization,left, is-success is-solid
enabled: true
concurrency: 10
input:
  Count: '1'
_inputMeta:
  Count:
    description: ''
    mandatory: true
workspace:
  endpoint: ''
  image: ''
  registry: ''
  path: ''
  autoCloneForTrigger: false
  limits:
    cpu: 1.0
    memory: 512
stageOrder:
- Stage0
stages:
  Stage0:
    taskOrder:
    - Task0
    tasks:
      Task0:
        type: Blueprint
        input:
          action: CreateDeployment
          deploymentName: TEST Pipeline ${requestBy} - ${executionId}
          blueprint: CentOS7 (vSphere)
          version: '4.2'
          parameters:
            Size: Small
            Network: PROD
            Count: ${input.Count}
